# Generated by Django 4.0.4 on 2022-04-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=150, verbose_name='Заказ')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.orders', verbose_name='Заказ'),
        ),
    ]
