# Generated by Django 4.0.4 on 2022-04-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_osa_gain_alter_osa_gain_flatness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='laser',
            field=models.ImageField(upload_to='copies/lasers/%Y/%m/%d', verbose_name='Технический паспорт лазера'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='passtopt',
            field=models.ImageField(upload_to='copies/passports/%Y/%m/%d', verbose_name='Технический паспорт изделия'),
        ),
    ]
