# Generated by Django 4.0.4 on 2022-04-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_documents_laser_alter_documents_passtopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectors',
            name='type',
            field=models.CharField(max_length=10, unique=True, verbose_name='Тип коннекторов'),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='mod',
            field=models.CharField(max_length=10, unique=True, verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.CharField(max_length=150, unique=True, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='technicals',
            name='p_eol',
            field=models.FloatField(verbose_name='Выходная мощность при максимальном токе'),
        ),
        migrations.AlterField(
            model_name='technicals',
            name='p_op',
            field=models.FloatField(verbose_name='Выходная мощность при рабочем токе'),
        ),
    ]
