# Generated by Django 4.0.4 on 2022-05-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_connectors_type_alter_modifications_mod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество изделий')),
                ('count_m12', models.IntegerField(verbose_name='Количество K25-M12')),
                ('count_n19', models.IntegerField(verbose_name='Количество K25_M19')),
                ('req_date', models.DateField(verbose_name='Дата заявки')),
                ('end_of_date', models.DateField(verbose_name='Дата окончания производства')),
                ('order', models.IntegerField(verbose_name='Номер заказа')),
                ('explanations', models.TextField(verbose_name='Пояснение')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('con_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.connectors', verbose_name='Тип коннектора')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'Заявки на производство',
                'ordering': ['req_date'],
            },
        ),
    ]
